### ISSUE TITLE
Clarification on Updating the Container

### ISSUE THREAD

**Issue by RON-SAE** [ffxvs/sd-webui-complete-setup#18]
Hi there,

Thanks so much for the guide on setting up Stable Diffusion Web UI - it’s been incredibly helpful and worked perfectly! Definitely the easiest guide I’ve come across.

I just had a quick question about updating the container. You mention that when a new version is available, "you have to create a new installation again." Does this mean I need to create a new notebook and reinstall the WebUI from scratch?

Thanks again for all your hard work!

**Comment by ffxvs** [comment]
> Does this mean I need to create a new notebook and reinstall the WebUI from scratch?

The short answer is yes, but I'll try to explain it further. It would be better if you [read this first](https://github.com/ffxvs/sd-webui-complete-setup/discussions/15#:~:text=paperspace%2Dstart.sh-,Updating,-To%20help%20you).

For example, currently Forge uses pytorch 2.3.1. Let's say next month the maintainer decides to update pytorch to version 2.4.0. We can still use pytorch 2.3.1, but it might not perform as well as 2.4.0. Because of that, I have no choice but to build a new container.

**Comment by RON-SAE** [comment]
Okay :D Thanks a lot for your quick and thorough answer!
