### ISSUE TITLE
after cicking update, cant start machine

### ISSUE THREAD

**Issue by gilroff** [ffxvs/sd-webui-complete-setup#2]
bash: /paperspace-start.sh: No such file or directory
{"what":"agent","message":"Loading settings configuration...","level":"info","timestamp":"2024-05-15T02:15:56.551Z"}
{"port":8889,"level":"info","message":"Started on","timestamp":"2024-05-15T02:15:56.553Z"}
{"message":"Finished initializing","level":"info","timestamp":"2024-05-15T02:15:56.554Z"}
bash: /paperspace-start.sh: No such file or directory

**Comment by ffxvs** [comment]
Never click the update button at the bottom because it will change the container to the Paperspace's default container. That's some kind of bug in Paperspace. Hence you need to create a new notebook. 

The latest container will be sent automatically every time you start the machine, so you don't need to do anything.

**Comment by gilroff** [comment]
Can I transfer my settings and loras and stuff from storage. if yes, how?

**Comment by ffxvs** [comment]
Just create a notebook in the same project. Your stuff is safe in shared storage.

[About shared storage](https://github.com/ffxvs/sd-webui-complete-setup/wiki/Paperspace-Guide#13-shared-storage)

**Comment by gilroff** [comment]
Oh okay thanks!
