### ISSUE TITLE
Webui.py does not exist in the jupyter notebook

### ISSUE THREAD

**Issue by Spy7Rik** [ffxvs/sd-webui-complete-setup#24]
Hello, first of all thank you a lot for your work and for sharing it, I ran into a problem trying to run the web ui,I managed to succesfully install my lora and my model , but when i try to launch the web ui an error message pops up saying that webui.py dose not exist in the notebook directory
![Capture d'écran 2024-11-07 211502](https://github.com/user-attachments/assets/d28d90cc-fe44-4a2c-8399-efd2d7ca70ae)
![Capture d'écran 2024-11-07 211428](https://github.com/user-attachments/assets/ee24702a-ada8-4fdc-b26d-af98df2dfa32)

**Comment by Spy7Rik** [comment]
it acutally was an error that occured during the installation, so i just started a new container and it fixed it self , thank yuo again for your amazing work!

**Comment by ffxvs** [comment]
Sorry I can't reply quickly. I just woke up.

Honestly, this is not the first time someone reporting the same issue. I don't know what caused it since I can't reproduce it because this never happened to me. 
As you said, there may be an error during the installation process on `1.1. Initialization` cell. WebUI is not installed correctly.

To solve this, you can delete the `stable-diffusion-webui` folder in the file browser and run the `1.1. Initialization` cell again. You don't need to install container from scratch again.

**Comment by Spy7Rik** [comment]
don't worry , i managed to fix the issue by installing everything again , thank you again for your amazing work !
