### ISSUE TITLE
update issue. clicking download doesnt work too

### ISSUE THREAD

**Issue by gilroff** [ffxvs/sd-webui-complete-setup#3]
Current version : 2024.03.24
Latest version  : 2024.05.20

There is new version

[Open Browser Console for more detailed log - Double click to close this message]
Model class 'OutputModel' from module '@jupyter-widgets/output' is loaded but can not be instantiated
TypeError: Cannot read properties of undefined (reading 'sessionContext')
    at u.initialize (https://console.paperspace.com/ide/vendors-f64a56cf.e313317ec5f436ec8fe5.js:2:159546)
    at new e.Model (https://console.paperspace.com/ide/vendors-c30f4496.e313317ec5f436ec8fe5.js:2:483011)
    at new u (https://console.paperspace.com/ide/vendors-f64a56cf.e313317ec5f436ec8fe5.js:2:159298)
    at z._make_model (https://console.paperspace.com/ide/vendors-f64a56cf.e313317ec5f436ec8fe5.js:2:11894)

**Comment by ffxvs** [comment]
It doesn't work if you try to download from the Paperspace console. Please use Jupyter Lab by clicking the orange circle icon in the side bar. But before doing that, duplicate your tab to keep the console open.
[Tips for using Jupyter Lab](https://github.com/ffxvs/sd-webui-complete-setup/wiki/Paperspace-Guide#tips)

In previous version, there was an error in the "Check for updates" cell where you downloaded the wrong file. Because of this, you cannot use the check for updates cell properly.

Therefore, you can get the latest updates automatically by deleting all jupyter notebooks starting with `sd_webui_`, `sd15_`, `sdxl_`, and then restart the machine. 

Or you can download the files manually from GitHub. There is a download button in the right corner : 
- [sd_webui_paperspace.ipynb](https://github.com/ffxvs/sd-webui-complete-setup/blob/main/sd-webui/sd_webui_paperspace.ipynb) 
- [sd_webui_forge_paperspace.ipynb](https://github.com/ffxvs/sd-webui-complete-setup/blob/main/sd-webui-forge/sd_webui_forge_paperspace.ipynb) (for Forge)
- [sd15_resource_lists.ipynb](https://github.com/ffxvs/sd-webui-complete-setup/blob/main/resource-lists/sd15_resource_lists.ipynb)
- [sdxl_resource_lists.ipynb](https://github.com/ffxvs/sd-webui-complete-setup/blob/main/resource-lists/sdxl_resource_lists.ipynb)

**Comment by gilroff** [comment]
Thanks, I deleted the notebooks and restarted the machine. Its working.
